return {
  require("lspconfig").jdtls.setup({
    cmd = {
      "java",
      "-Declipse.application=org.eclipse.jdt.ls.core.id1",
      "-Dosgi.bundles.defaultStartLevel=4",
      "-Declipse.product=org.eclipse.jdt.ls.core.product",
      "-Dlog.protocol=true",
      "-Dlog.level=ALL",
      "-Xmx2G",
      "--add-modules=ALL-SYSTEM",
      "--add-opens",
      "java.base/java.util=ALL-UNNAMED",
      "--add-opens",
      "java.base/java.lang=ALL-UNNAMED",
      "-javaagent:" .. vim.fn.expand("~/.config/nvim/lombok.jar"),
      "-jar",
      vim.fn.glob("~/.local/share/nvim/mason/packages/jdtls/plugins/org.eclipse.equinox.launcher_*.jar"),
      "-configuration",
      vim.fn.expand("~/.local/share/nvim/mason/packages/jdtls/config_linux"),
      "-data",
      vim.fn.expand("~/.cache/nvim/jdtls/workspace"),
    },
    root_dir = require("lspconfig.util").root_pattern("pom.xml", ".git", "build.gradle"),
  }),
}
